# This file was generated by GoReleaser. DO NOT EDIT.
cask "envseal" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "86d418be734ac834f64b8760f99c78372e2f87c23a1c71197496239d6fcb8845"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99ccac66811d1535c0b2ada7fc02863c18d0d5da13c670274894d569dc041477"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "030a1cb9d1a41ea006cbd8707c33cb4e2d136e37c333c356178c0e1934548bbd"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d599f4c5f00dcdc4e54bb3af4bd2d5b17e8eac613dfe6813161328c677c9cb30"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envseal"
  desc "Git-friendly encrypted .env files"
  homepage "https://github.com/PeacexF/envseal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envseal"
  bash_completion "completions/envseal.bash"
  fish_completion "completions/envseal.fish"
  zsh_completion "completions/_envseal"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/envseal"
    end
  end

  # No zap stanza required

end
