# This file was generated by GoReleaser. DO NOT EDIT.
cask "envseal" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "3cafcfc99e6fb4275e72808eb8795e247b6bf5cc1ce44830e6ccc674f169b17a"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f0df028f04e136587df60e9f75cee66238749d95b5f32c393be181df7173f9e"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7af455a788dbe758d619a3032530a34fbac82ef2d2202960d7adf36766f5002"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be6928873fe75137b187d7348f56f8e2088be8d96a27cfeb434519fcfbe7cb4f"
      url "https://github.com/PeacexF/envseal/releases/download/v#{version}/envseal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envseal"
  desc "Git-friendly encrypted .env files"
  homepage "https://github.com/PeacexF/envseal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envseal"
  bash_completion "completions/envseal.bash"
  fish_completion "completions/envseal.fish"
  zsh_completion "completions/_envseal"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/envseal"
    end
  end

  # No zap stanza required

end
