# This file was generated by GoReleaser. DO NOT EDIT.
cask "stinger" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "61a1ee52bd6af6ffaa2db8a938b4199d1263e754d63daf36b159637fde8ed086"
      url "https://github.com/PeacexF/Stinger/releases/download/v#{version}/stinger_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa50086df08015a392e037a6ae0015cb839ceb2d5a3c651deeb9b7a06fc2257f"
      url "https://github.com/PeacexF/Stinger/releases/download/v#{version}/stinger_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d28c9ce1e016561ec109741c909d50471b1cbb93e66c8b3b09ea188a72cd2c84"
      url "https://github.com/PeacexF/Stinger/releases/download/v#{version}/stinger_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd888d1de500376945ef29f865cbdd3e3847cb27b45bdfff05583d14a0622a80"
      url "https://github.com/PeacexF/Stinger/releases/download/v#{version}/stinger_#{version}_linux_amd64.tar.gz"
    end
  end

  name "stinger"
  desc "High-performance SMTP email verifier"
  homepage "https://github.com/PeacexF/Stinger"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stinger"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stinger"]
    end
  end

  # No zap stanza required
end
